/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoHoiKinhDoanhRouteImport } from './routes/co-hoi-kinh-doanh'
import { Route as DangNhapRouteImport } from './routes/dang-nhap'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as QuanLyRouteImport } from './routes/quan-ly'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as UuDaiRouteImport } from './routes/uu-dai'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoHoiKinhDoanhRoute = CoHoiKinhDoanhRouteImport.update({
  id: '/co-hoi-kinh-doanh',
  path: '/co-hoi-kinh-doanh',
  getParentRoute: () => rootRouteImport,
} as any)
const DangNhapRoute = DangNhapRouteImport.update({
  id: '/dang-nhap',
  path: '/dang-nhap',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const QuanLyRoute = QuanLyRouteImport.update({
  id: '/quan-ly',
  path: '/quan-ly',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const UuDaiRoute = UuDaiRouteImport.update({
  id: '/uu-dai',
  path: '/uu-dai',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/co-hoi-kinh-doanh': typeof CoHoiKinhDoanhRoute
  '/dang-nhap': typeof DangNhapRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/quan-ly': typeof QuanLyRoute
  '/shops': typeof ShopsRoute
  '/uu-dai': typeof UuDaiRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/co-hoi-kinh-doanh': typeof CoHoiKinhDoanhRoute
  '/dang-nhap': typeof DangNhapRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/quan-ly': typeof QuanLyRoute
  '/shops': typeof ShopsRoute
  '/uu-dai': typeof UuDaiRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/co-hoi-kinh-doanh': typeof CoHoiKinhDoanhRoute
  '/dang-nhap': typeof DangNhapRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/quan-ly': typeof QuanLyRoute
  '/shops': typeof ShopsRoute
  '/uu-dai': typeof UuDaiRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/co-hoi-kinh-doanh'
    | '/dang-nhap'
    | '/gioi-thieu'
    | '/quan-ly'
    | '/shops'
    | '/uu-dai'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/co-hoi-kinh-doanh'
    | '/dang-nhap'
    | '/gioi-thieu'
    | '/quan-ly'
    | '/shops'
    | '/uu-dai'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/co-hoi-kinh-doanh'
    | '/dang-nhap'
    | '/gioi-thieu'
    | '/quan-ly'
    | '/shops'
    | '/uu-dai'
    | '/shop/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoHoiKinhDoanhRoute: typeof CoHoiKinhDoanhRoute
  DangNhapRoute: typeof DangNhapRoute
  GioiThieuRoute: typeof GioiThieuRoute
  QuanLyRoute: typeof QuanLyRoute
  ShopsRoute: typeof ShopsRoute
  UuDaiRoute: typeof UuDaiRoute
  ShopSlugRoute: typeof ShopSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-hoi-kinh-doanh': {
      id: '/co-hoi-kinh-doanh'
      path: '/co-hoi-kinh-doanh'
      fullPath: '/co-hoi-kinh-doanh'
      preLoaderRoute: typeof CoHoiKinhDoanhRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dang-nhap': {
      id: '/dang-nhap'
      path: '/dang-nhap'
      fullPath: '/dang-nhap'
      preLoaderRoute: typeof DangNhapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quan-ly': {
      id: '/quan-ly'
      path: '/quan-ly'
      fullPath: '/quan-ly'
      preLoaderRoute: typeof QuanLyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uu-dai': {
      id: '/uu-dai'
      path: '/uu-dai'
      fullPath: '/uu-dai'
      preLoaderRoute: typeof UuDaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoHoiKinhDoanhRoute: CoHoiKinhDoanhRoute,
  DangNhapRoute: DangNhapRoute,
  GioiThieuRoute: GioiThieuRoute,
  QuanLyRoute: QuanLyRoute,
  ShopsRoute: ShopsRoute,
  UuDaiRoute: UuDaiRoute,
  ShopSlugRoute: ShopSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
