/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as UuDaiRouteImport } from './routes/uu-dai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const UuDaiRoute = UuDaiRouteImport.update({
  id: '/uu-dai',
  path: '/uu-dai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/shops': typeof ShopsRoute
  '/uu-dai': typeof UuDaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/shops': typeof ShopsRoute
  '/uu-dai': typeof UuDaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/shops': typeof ShopsRoute
  '/uu-dai': typeof UuDaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gioi-thieu' | '/shops' | '/uu-dai'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gioi-thieu' | '/shops' | '/uu-dai'
  id: '__root__' | '/' | '/gioi-thieu' | '/shops' | '/uu-dai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GioiThieuRoute: typeof GioiThieuRoute
  ShopsRoute: typeof ShopsRoute
  UuDaiRoute: typeof UuDaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uu-dai': {
      id: '/uu-dai'
      path: '/uu-dai'
      fullPath: '/uu-dai'
      preLoaderRoute: typeof UuDaiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GioiThieuRoute: GioiThieuRoute,
  ShopsRoute: ShopsRoute,
  UuDaiRoute: UuDaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
